apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  type: NodePort                  # NodePort for local access
  selector:
    app: blog-app
  ports:
    - port: 8081                  # internal cluster port
      targetPort: 8081            # container port in pod
      nodePort: 30007             # external port to access app
