name: Spring Boot CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Build Spring Boot app with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Build Docker image
      - name: Build Docker Image
        run: docker build -t blog-app .

      # Step 5: Login to Docker Hub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      # Step 6: Tag image with unique version
      - name: Tag Image
        run: docker tag blog-app ${{ secrets.DOCKER_USER }}/blog-app:${{ github.sha }}

      # Step 7: Push image
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USER }}/blog-app:${{ github.sha }}

      # Step 8: Clone GitOps repo (WITH TOKEN ✅)
      - name: Clone GitOps repo
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/Thanushpalavalasa/blog-app-gitops.git

      # Step 9: Update deployment.yaml image
      - name: Update deployment image
        run: |
          cd blog-app-gitops
          sed -i 's|image: .*|image: '${{ secrets.DOCKER_USER }}'/blog-app:${{ github.sha }}|' deployment.yaml

      # Step 10: Commit and push changes
      - name: Commit and push changes
        run: |
          cd blog-app-gitops
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
          git remote set-url origin https://${{ secrets.GIT_TOKEN }}@github.com/Thanushpalavalasa/blog-app-gitops.git
          git push
